// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSkFZzH5rRZbF8g6qKqxaE5_SpvUNr5kU',
    appId: '1:68444770162:android:d15e6e23717cd0eed717eb',
    messagingSenderId: '68444770162',
    projectId: 'alive-dsm',
    databaseURL: 'https://alive-dsm-default-rtdb.firebaseio.com',
    storageBucket: 'alive-dsm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjCT-kGI6UR0XdSr36ki4RnHd3wk_miFg',
    appId: '1:68444770162:ios:a15ee85668d496bdd717eb',
    messagingSenderId: '68444770162',
    projectId: 'alive-dsm',
    databaseURL: 'https://alive-dsm-default-rtdb.firebaseio.com',
    storageBucket: 'alive-dsm.appspot.com',
    iosClientId:
        '68444770162-ulmp0sihb38886koflhddnlthhn866ce.apps.googleusercontent.com',
    iosBundleId: 'com.iiitd.inductionteam2023.btechInduction2023',
  );
}
